#! /bin/sh

# Spaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# Border
bspc config border_width          2
bspc config normal_border_color   "#262626"
bspc config focused_border_color  "#d75fd7"
# bspc config urgent_border_color   "#B58900"
# bspc config presel_border_color   "#26E2FF"

# Split
bspc config window_gap            2 # default 12
bspc config split_ratio           0.50

# Monocle
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# Focus
bspc config focus_follows_pointer false
bspc config history_aware_focus   true
bspc config focus_by_distance     true

# Rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
